# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42d550b392ab1534d80f57f5f85dfaccd447a2653cede52f701adba0c83bdd9d0a241f8318a9180ce3d801980c487220d5bbc21f1d5a7e54cd165360875690a9

test:
  secret_key_base: 541536003a02b51f8a243aea9f09b06ffb2be68b23cf2245a027b95f981ae2dadb57827dad9b9444a5416603f3c46612438d3280d7698c422af4074c9e61fcf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
